apiVersion: functions.nephio.org/v1alpha1
kind: ApplyClusterScaleProfile
metadata:
  name: fn-config-apply-scale-profile
  annotations:
    config.kubernetes.io/local-config: "true"
profile: small-fixed-site
configMaps:
- name: nginx-configmap
  key: nginx.conf
deployments:
- name: nginx-deployment
  lowDensity:
    replicas: 1
    containers:
    - name: nginx
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
  mediumDensity:
    replicas: 3
    containers:
    - name: nginx
      resources:
        requests:
          memory: "64Mi"
          cpu: "750m"
        limits:
          memory: "256Mi"
          cpu: "1500m"
  highDensity:
    replicas: 9
    containers:
    - name: nginx
      resources:
        requests:
          memory: "64Mi"
          cpu: "1000m"
        limits:
          memory: "256Mi"
          cpu: "3000m"
